Euroquiz.eurovision = {
	videos: [
		{ year: 2013, country: 'Albania', id: '_Pf-ZCI-UuA' },
		{ year: 2013, country: 'Armenia', id: 'JSs03Sp-4ME' },
		{ year: 2013, country: 'Austria', id: '1RPLzJ5hqYc' },
		{ year: 2013, country: 'Azerbaijan', id: 'r5egVzkZGTg' },
		{ year: 2013, country: 'Belarus', id: 'N4S4m9R-ffA' },
		{ year: 2013, country: 'Belgium', id: 'C9uExokZcIM' },
		{ year: 2013, country: 'Bulgaria', id: 'bExp3aNOFsE' },
		{ year: 2013, country: 'Croatia', id: 'LQDGlNnhBvI' },
		{ year: 2013, country: 'Cyprus', id: 'OEd1TsVBo9U' },
		{ year: 2013, country: 'Denmark', id: 'k59E7T0H-Us' },
		{ year: 2013, country: 'Estonia', id: '02uHFbCN2JI' },
		{ year: 2013, country: 'F.Y.R. Macedonia', id: '-LwGGo5ZfF8' },
		{ year: 2013, country: 'Finland', id: 'FdU02F9lT2g' },
		{ year: 2013, country: 'France', id: 'YQJaab8j4fU' },
		{ year: 2013, country: 'Georgia', id: 'CvdcRmzuXKM' },
		{ year: 2013, country: 'Germany', id: 's8LPaowU9js' },
		{ year: 2013, country: 'Greece', id: 'G3k2MOJOkKg' },
		{ year: 2013, country: 'Hungary', id: 'UmjsIhihJMY' },
		{ year: 2013, country: 'Iceland', id: 'PtunhyMW1hM' },
		{ year: 2013, country: 'Ireland', id: 'iGaZKoim43U' },
		{ year: 2013, country: 'Israel', id: 'rYuSe5h-rrg' },
		{ year: 2013, country: 'Italy', id: 'X2C-ePvHfAs' },
		{ year: 2013, country: 'Latvia', id: 'P4lwr-zMSnM' },
		{ year: 2013, country: 'Lithuania', id: 'MCZ6RRwKcIE' },
		{ year: 2013, country: 'Malta', id: '8WmJXIR9xtw' },
		{ year: 2013, country: 'Moldova', id: 'nkbEkuk2TKM' },
		{ year: 2013, country: 'Montenegro', id: '8BmHI_57vJk' },
		{ year: 2013, country: 'Norway', id: 'gjm-kCOMaPY' },
		{ year: 2013, country: 'Romania', id: '8pNEEb6dzi8' },
		{ year: 2013, country: 'Russia', id: '1VwzdeRNjtA' },
		{ year: 2013, country: 'San Marino', id: 'xi8mZ2ejLcE' },
		{ year: 2013, country: 'Serbia', id: 'LW7TAdytfww' },
		{ year: 2013, country: 'Slovenia', id: 'SqL0SP3zARg' },
		{ year: 2013, country: 'Spain', id: 'Q5m8aCZSvws' },
		{ year: 2013, country: 'Sweden', id: 'jBUJ0u7ZVaE' },
		{ year: 2013, country: 'Switzerland', id: 'fBGpqq2LFSQ' },
		{ year: 2013, country: 'The Netherlands', id: '1vtOwHHDAFc' },
		{ year: 2013, country: 'Ukraine', id: '-onH40yB2uk' },
		{ year: 2013, country: 'United Kingdom', id: 'HALTU11QE6g' },
		{ year: 2012, country: 'Albania', id: 'v9zIP4FA-1Y' },
		{ year: 2012, country: 'Austria', id: 'BKQf8Z5uWQ8' },
		{ year: 2012, country: 'Azerbaijan', id: '-8ejpLyXSuY' },
		{ year: 2012, country: 'Belarus', id: 'hnJZG0eyavs' },
		{ year: 2012, country: 'Belgium', id: '5pGWkV7y6As' },
		{ year: 2012, country: 'Bosnia & Herzegovina', id: 'v_fyisw2--M' },
		{ year: 2012, country: 'Bulgaria', id: 'zM4kCl-yKgo' },
		{ year: 2012, country: 'Croatia', id: 'z5_tqyCjFZ8' },
		{ year: 2012, country: 'Cyprus', id: 'Pedf_OQmcmI' },
		{ year: 2012, country: 'Denmark', id: '6nR9nsKTx4g' },
		{ year: 2012, country: 'Estonia', id: 'PSQdnvzV8CE' },
		{ year: 2012, country: 'F.Y.R. Macedonia', id: '98FZchoQxvc' },
		{ year: 2012, country: 'Finland', id: '43GWoVxRk2Y' },
		{ year: 2012, country: 'France', id: 'SnSmB7uBo-Y' },
		{ year: 2012, country: 'Georgia', id: 'o1kCgD626Go' },
		{ year: 2012, country: 'Germany', id: 'MxA6TWLttZo' },
		{ year: 2012, country: 'Greece', id: 'isPtzi5cxBg' },
		{ year: 2012, country: 'Hungary', id: 'qVXhElLlWb8' },
		{ year: 2012, country: 'Iceland', id: 'p8RS0eulXDo' },
		{ year: 2012, country: 'Ireland', id: 'D_ViQfViDPo' },
		{ year: 2012, country: 'Israel', id: 'lWMH6ID6Enc' },
		{ year: 2012, country: 'Italy', id: '1K8PB8eIy50' },
		{ year: 2012, country: 'Latvia', id: '_CzSRTGq6Ds' },
		{ year: 2012, country: 'Lithuania', id: '28Zel35BCwo' },
		{ year: 2012, country: 'Malta', id: 'cjhBsCop3Ys' },
		{ year: 2012, country: 'Moldova', id: '3H7AILnPoio' },
		{ year: 2012, country: 'Montenegro', id: 'D6S-FNLv2jQ' },
		{ year: 2012, country: 'Norway', id: 'fOdRFtwTzb8' },
		{ year: 2012, country: 'Portugal', id: 'PPJUJHLGhA8' },
		{ year: 2012, country: 'Romania', id: 'VH2t9LpRGQk' },
		{ year: 2012, country: 'Russia', id: 'WKNRGc71hjc' },
		{ year: 2012, country: 'San Marino', id: 'PqwBh9hq9PE' },
		{ year: 2012, country: 'Serbia', id: '75weifR47m0' },
		{ year: 2012, country: 'Slovakia', id: 'z2_7YdLk1Tc' },
		{ year: 2012, country: 'Slovenia', id: 'SUrkusKotaA' },
		{ year: 2012, country: 'Spain', id: 'fL-s0eRRYTE' },
		{ year: 2012, country: 'Sweden', id: '4nJcmLMb5to' },
		{ year: 2012, country: 'Switzerland', id: '8yX1dIK9vuc' },
		{ year: 2012, country: 'The Netherlands', id: 'zfofDgg-Jww' },
		{ year: 2012, country: 'Turkey', id: '7PneOwzMz4M' },
		{ year: 2012, country: 'Ukraine', id: 'i-LyyCxlSFc' },
		{ year: 2012, country: 'United Kingdom', id: 'pFNv9pjqZkk' },
		{ year: 2011, country: 'Albania', id: '35yy7Ls3ptc' },
		{ year: 2011, country: 'Armenia', id: '_OO7p_iKwAk' },
		{ year: 2011, country: 'Austria', id: 's88qtWo7byY' },
		{ year: 2011, country: 'Azerbaijan', id: 'vvZlEAP5Z28' },
		{ year: 2011, country: 'Belarus', id: 'Asz9f-9SxiE' },
		{ year: 2011, country: 'Belgium', id: 'ZD09ThCx4Cw' },
		{ year: 2011, country: 'Bosnia & Herzegovina', id: 'urqhlnWLXxs' },
		{ year: 2011, country: 'Bulgaria', id: 'I4naw9iUrTw' },
		{ year: 2011, country: 'Croatia', id: 'dtcsw6vLENg' },
		{ year: 2011, country: 'Cyprus', id: 'fmGLd3zqW9Q' },
		{ year: 2011, country: 'Denmark', id: 'aGVZktHLZhk' },
		{ year: 2011, country: 'Estonia', id: 'kXFGFCRV3z0' },
		{ year: 2011, country: 'F.Y.R. Macedonia', id: 'NRG2lY9CuL8' },
		{ year: 2011, country: 'Finland', id: 'h65xXOVrQzQ' },
		{ year: 2011, country: 'France', id: 'uEb7hRo-Qyk' },
		{ year: 2011, country: 'Georgia', id: 'LvnLWlHqMqM' },
		{ year: 2011, country: 'Germany', id: '44ydDZlsruk' },
		{ year: 2011, country: 'Greece', id: 'jtaD4Ayt0kg' },
		{ year: 2011, country: 'Hungary', id: 'Wy_oB_FYd7s' },
		{ year: 2011, country: 'Iceland', id: 'foI2HlqsWQk' },
		{ year: 2011, country: 'Ireland', id: '75ux9AvDPfI' },
		{ year: 2011, country: 'Israel', id: 'JmBMQJlzTa4' },
		{ year: 2011, country: 'Italy', id: 'tO0Ih3q4PSE' },
		{ year: 2011, country: 'Latvia', id: '4OCUTGmCums' },
		{ year: 2011, country: 'Lithuania', id: 'BWsuBnfYQBw' },
		{ year: 2011, country: 'Malta', id: 'SYQnPY0znPA' },
		{ year: 2011, country: 'Moldova', id: 'GXTm9yKP4_4' },
		{ year: 2011, country: 'Norway', id: 'o7W-ko3Bbt8' },
		{ year: 2011, country: 'Poland', id: 'vkm6hCiuyXw' },
		{ year: 2011, country: 'Portugal', id: 'gDBjUoty-zE' },
		{ year: 2011, country: 'Romania', id: '7PnaTmV5I1Q' },
		{ year: 2011, country: 'Russia', id: 'rpiXxV3y8H0' },
		{ year: 2011, country: 'San Marino', id: 'Owh0pnNzh0Y' },
		{ year: 2011, country: 'Serbia', id: 'jC8hu_9lonw' },
		{ year: 2011, country: 'Slovakia', id: 'bt8QhxICZzA' },
		{ year: 2011, country: 'Slovenia', id: 'NM8QpZMjNpg' },
		{ year: 2011, country: 'Spain', id: 'IYzomDkiORw' },
		{ year: 2011, country: 'Sweden', id: 'iEX0WSq2jh4' },
		{ year: 2011, country: 'Switzerland', id: 'PtlhYGVtZlk' },
		{ year: 2011, country: 'The Netherlands', id: 'KlneiG2bGuE' },
		{ year: 2011, country: 'Turkey', id: '0QUDFPmcWgw' },
		{ year: 2011, country: 'Ukraine', id: 'Jtfetx1u8I0' },
		{ year: 2011, country: 'United Kingdom', id: 'mRU31ieUhJM' }
	],
	countries: [
		'Albania',
		'Armenia',
		'Austria',
		'Azerbaijan',
		'Belarus',
		'Belgium',
		'Bosnia & Herzegovina',
		'Bulgaria',
		'Croatia',
		'Cyprus',
		'Denmark',
		'Estonia',
		'F.Y.R. Macedonia',
		'Finland',
		'France',
		'Georgia',
		'Germany',
		'Greece',
		'Hungary',
		'Iceland',
		'Ireland',
		'Israel',
		'Italy',
		'Latvia',
		'Lithuania',
		'Malta',
		'Moldova',
		'Montenegro',
		'Norway',
		'Poland',
		'Portugal',
		'Romania',
		'Russia',
		'San Marino',
		'Serbia',
		'Slovakia',
		'Slovenia',
		'Spain',
		'Sweden',
		'Switzerland',
		'The Netherlands',
		'Turkey',
		'Ukraine',
		'United Kingdom'
	]
};