Euroquiz.eurovision = {
	videos: [
		{ country: 'San Marino', id: 'PqwBh9hq9PE' },
		{ country: 'Serbia', id: '75weifR47m0' },
		{ country: 'France', id: 'SnSmB7uBo-Y' },
		{ country: 'Italy', id: '1K8PB8eIy50' },
		{ country: 'Moldova', id: '3H7AILnPoio' },
		{ country: 'Georgia', id: 'o1kCgD626Go' },
		{ country: 'Bulgaria', id: 'zM4kCl-yKgo' },
		{ country: 'Azerbaijan', id: '-8ejpLyXSuY' },
		{ country: 'Romania', id: 'VH2t9LpRGQk' },
		{ country: 'Hungary', id: 'qVXhElLlWb8' },
		{ country: 'Croatia', id: 'z5_tqyCjFZ8' },
		{ country: 'United Kingdom', id: 'pFNv9pjqZkk' },
		{ country: 'Montenegro', id: 'D6S-FNLv2jQ' },
		{ country: 'Belgium', id: '5pGWkV7y6As' },
		{ country: 'F.Y.R. Macedonia', id: '98FZchoQxvc' },
		{ country: 'Iceland', id: 'p8RS0eulXDo' },
		{ country: 'Malta', id: 'cjhBsCop3Ys' },
		{ country: 'Spain', id: 'fL-s0eRRYTE' },
		{ country: 'Albania', id: 'v9zIP4FA-1Y' },
		{ country: 'Belarus', id: 'hnJZG0eyavs' },
		{ country: 'Latvia', id: '_CzSRTGq6Ds' },
		{ country: 'Bosnia & Herzegovina', id: 'v_fyisw2--M' },
		{ country: 'Estonia', id: 'PSQdnvzV8CE' },
		{ country: 'Cyprus', id: 'Pedf_OQmcmI' },
		{ country: 'Ukraine', id: 'i-LyyCxlSFc' },
		{ country: 'The Netherlands', id: 'zfofDgg-Jww' },
		{ country: 'Turkey', id: '7PneOwzMz4M' },
		{ country: 'Greece', id: 'isPtzi5cxBg' },
		{ country: 'Slovakia', id: 'z2_7YdLk1Tc' },
		{ country: 'Portugal', id: 'PPJUJHLGhA8' },
		{ country: 'Finland', id: '43GWoVxRk2Y' },
		{ country: 'Lithuania', id: '28Zel35BCwo' },
		{ country: 'Ireland', id: 'D_ViQfViDPo' },
		{ country: 'Switzerland', id: '8yX1dIK9vuc' },
		{ country: 'Israel', id: 'lWMH6ID6Enc' },
		{ country: 'Russia', id: 'WKNRGc71hjc' },
		{ country: 'Slovenia', id: 'SUrkusKotaA' },
		{ country: 'Germany', id: 'MxA6TWLttZo' },
		{ country: 'Sweden', id: '4nJcmLMb5to' },
		{ country: 'Austria', id: 'BKQf8Z5uWQ8' },
		{ country: 'Norway', id: 'fOdRFtwTzb8' },
		{ country: 'Denmark', id: '6nR9nsKTx4g' }
	],
	countries: [
		'San Marino',
		'Serbia',
		'France',
		'Italy',
		'Moldova',
		'Georgia',
		'Bulgaria',
		'Azerbaijan',
		'Romania',
		'Hungary',
		'Croatia',
		'United Kingdom',
		'Montenegro',
		'Belgium',
		'F.Y.R. Macedonia',
		'Iceland',
		'Malta',
		'Spain',
		'Albania',
		'Belarus',
		'Latvia',
		'Bosnia & Herzegovina',
		'Estonia',
		'Cyprus',
		'Ukraine',
		'The Netherlands',
		'Turkey',
		'Greece',
		'Slovakia',
		'Portugal',
		'Finland',
		'Lithuania',
		'Ireland',
		'Switzerland',
		'Israel',
		'Russia',
		'Slovenia',
		'Germany',
		'Sweden',
		'Austria',
		'Norway',
		'Denmark'
	]
};